include:
  - template: SAST.gitlab-ci.yml

image: gcc

build:
  stage: build
  before_script:
    - apt update && apt -y install make
  script:
    - make all
  artifacts:
    paths:
      - "./bin/swuniq"

build-static:  
  stage: build
  before_script:
    - apt update && apt -y install make
  script:
    - make static
  artifacts:
    paths:
      - "./bin/static/swuniq"

# run tests using the binary built before
test:
  stage: test
  script:
    - ./bin/swuniq -h || exit 0

# run tests using the binary built before
test-static:
  stage: test
  script:
    - ./bin/static/swuniq -h || exit 0

