name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ${{ platform.os }}
    strategy:
      platform:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: make
