name: Build swuniq

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: make
